name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./three-js
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0

      - name: Install dependencies
        run: npm i 

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./three-js/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - uses: actions/checkout@v3

        - uses: actions/download-artifact@v3
          id: download
          with:
            name: production-files
            path: ./three-js/dist